"""Added update

Revision ID: e99569a85afe
Revises: 
Create Date: 2025-01-23 17:21:24.768919

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e99569a85afe"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("salary", sa.Integer(), nullable=False),
        sa.Column("gender", sa.String(length=10), nullable=True),
        sa.Column("date_of_birth", sa.Date(), nullable=True),
        sa.Column("time_created", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "claim",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("diagnosis", sa.String(length=1000), nullable=True),
        sa.Column("hmo", sa.String(length=4), nullable=True),
        sa.Column("age", sa.Integer(), nullable=True),
        sa.Column("service_charge", sa.Integer(), nullable=True),
        sa.Column("total_cost", sa.Integer(), nullable=True),
        sa.Column("final_cost", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "service",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("claim_id", sa.Integer(), nullable=True),
        sa.Column("service_date", sa.DateTime(), nullable=False),
        sa.Column("service_name", sa.String(length=100), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("provider_name", sa.String(length=100), nullable=False),
        sa.Column("source", sa.String(length=100), nullable=False),
        sa.Column("cost_of_service", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["claim_id"],
            ["claim.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider_name"),
        sa.UniqueConstraint("service_name"),
        sa.UniqueConstraint("source"),
        sa.UniqueConstraint("type"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("service")
    op.drop_table("claim")
    op.drop_table("user")
    # ### end Alembic commands ###
