"""Added gender to claim

Revision ID: eec1bea07e15
Revises: e99569a85afe
Create Date: 2025-01-23 19:25:26.307287

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "eec1bea07e15"
down_revision = "e99569a85afe"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("claim", schema=None) as batch_op:
        batch_op.add_column(sa.Column("is_male", sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("claim", schema=None) as batch_op:
        batch_op.drop_column("is_male")

    # ### end Alembic commands ###
