"""Init

Revision ID: f395b1ed7c72
Revises: eec1bea07e15
Create Date: 2025-01-24 15:55:18.208509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f395b1ed7c72'
down_revision = 'eec1bea07e15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('claim', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('in progress', 'sent', 'paid'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('claim', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
